# colors
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

# bash history
HISTCONTROL=erasedups
HISTSIZE=1000000000
HISTFILESIZE=2000000000

shopt -s histappend

# paths
MY_BIN="$HOME/.mybin:$HOME/Development/scripture"
CABAL_BIN="$HOME/.cabal/cabal:$HOME/.cabal/bin"
#QT5_BIN="/usr/local/Cellar/qt5/5.3.2/bin"
export PATH="$MY_BIN:$CABAL_BIN:/usr/local/sbin:/usr/local/bin:$PATH"

# homebrew
export HOMEBREW_BUILD_FROM_SOURCE=1
export HOMEBREW_NO_ANALYTICS=1

# ruby
eval "$(rbenv init -)"
